version: "2"
services:
  rs-Arbiter-1:
    image: "mongo-start"
    buiuld: ./rs-Arbiter-1
    ports:
      - "27017:27017"
    volumes:
      - ./rs-Arbiter-1/database:data/db
    depends_on:
      - "rs-Master-2"
      - "rs-Slave-3"

  rs-Master-2:
    image: "mongo"
    command: --replSet rs0 --smallfile --oplogSize 128
    ports:
      - "27018:27017"
    volumes:
      - ./rs-Master-2/database:data/db

  rs-Slave-3:
    image: "mongo"
    command: --replSet rs0 --smallfile --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./rs-Slave/database:data/db
